adminUser:
  password: local:jx-kube-cluster/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: gparmar8653@gmail.com
  token: local:jx-kube-cluster/pipelineUser:token
  username: parmar-gaurav-devops
prow:
  hmacToken: local:jx-kube-cluster/prow:hmacToken
